### ISSUE TITLE
CustomResourcePack crashes on startup

### ISSUE THREAD

**Issue by TheCurle** [Low-Drag-MC/LDLib-MultiLoader#10]
[crash-2023-08-28_20.45.05-client.txt](https://github.com/Low-Drag-MC/LDLib-Architectury/files/12457360/crash-2023-08-28_20.45.05-client.txt)

I am running a decently large server using the ATM9 pack, and a good portion of my users started having this crash on startup after we updated to 0.0.59. Little other information is known.

**Comment by screret** [comment]
@Yefancy big issue

**Comment by KitsuTheFloof** [comment]
I'm having the same issue

**Comment by Yefancy** [comment]
fixed in 1.0.19.d
