### ISSUE TITLE
AE2 Processing Pattern Encoding Not working on REI

### ISSUE THREAD

**Issue by Drackion** [Low-Drag-MC/LDLib-MultiLoader#11]
When REI is use as the Recipe viewer and REI compat is installed any pack with gregtech the encoding of ae2 processing patterns doesn't working as it only encodes only fluid:

Video:

https://github.com/Low-Drag-MC/LDLib-Architectury/assets/64641342/bf31a73c-6feb-4471-ab8b-97422ccc372d

I also talked about the issue on the Kubejs discord and they looked at the LDlib code an atributed the issue to missing annotation is the JEI plugin:

https://github.com/Low-Drag-MC/LDLib-Architectury/blob/1.19.2/common/src/main/java/com/lowdragmc/lowdraglib/jei/JEIPlugin.java#L25

![image](https://github.com/Low-Drag-MC/LDLib-Architectury/assets/64641342/661f08c0-8fcc-43b9-a362-8d0fc65fb6fd)

**Comment by LKD-PIX** [comment]
can confirm this issue, but it may be due to the REI-JEI adapter component mod being present
