### ISSUE TITLE
[1.20.1] - Server crash

### ISSUE THREAD

**Issue by aking4125** [Low-Drag-MC/LDLib-MultiLoader#16]
Hello, upon adding this mod. The server crashes with the following report:

[crash-2024-02-14_03.10.47-fml.txt](https://github.com/Low-Drag-MC/LDLib-Architectury/files/14276990/crash-2024-02-14_03.10.47-fml.txt)

Also the issue tab on the curseforge page points to the old repository which is archived. Dunno if this should be posted here or there but the issue tab there might need updating. Issues are being posted there as well. If this is not the correct location for this issue, please let me know.

**Comment by Yefancy** [comment]
thank you very much. I just fixed it in the latest 1.0.24.a
