### ISSUE TITLE
Server freezes during restart

### ISSUE THREAD

**Issue by BazZziliuS** [Low-Drag-MC/LDLib-MultiLoader#26]
Hi, I ran into an error that causes the server to stall when restarting
I use the [gtсeu](https://modrinth.com/mod/gregtechceu-modern/version/mc1.20.1-1.3.1) mod of the latest version in which the ldlib-forge library is 1.20.1-1.0.25.p
[debug.log](https://paste.fuix.net/A8HBBrn)

Let me know if you need more information. This problem is quite serious because I have to stay awake to restart the server manually

**Comment by Yefancy** [comment]
it only happens while restarting?
what kind of special server are you using? (cat, forge, etc..)

**Comment by sanik** [comment]
1.20.1 Mohist

**Comment by BazZziliuS** [comment]
> it only happens while restarting? what kind of special server are you using? (cat, forge, etc..)

As answered above by Mohist: 1.20.1-755

**Comment by Yefancy** [comment]
I hope it got fixed since the 1.0.29.b. reopen it if not
