### ISSUE TITLE
Conflict with JEI

### ISSUE THREAD

**Issue by etmclovin** [Low-Drag-MC/LDLib-MultiLoader#31]
I recently opened an issue on the JEI issue tracker after realising it was an LDLib issue i was told to open an issue here. Im aware that there was a problem with a buggy mixin that is being worked on. Thanks for your help

https://github.com/mezz/JustEnoughItems/issues/3642

**Comment by Periam** [comment]
I have the same issue below are the logs from mine.

[debug.log](https://github.com/user-attachments/files/16565033/debug.log)
[latest.log](https://github.com/user-attachments/files/16565034/latest.log)
[crash-2024-08-09_14.39.25-client.txt](https://github.com/user-attachments/files/16565040/crash-2024-08-09_14.39.25-client.txt)
