### ISSUE TITLE
Where did FluidStack / ItemStackTransfer go?

### ISSUE THREAD

**Issue by yu-re-ka** [Low-Drag-MC/LDLib-MultiLoader#37]
Hi,

I'm trying to build a version of Gregic Energestics for Minecraft 1.21 Neoforge.
I've ported over most of the Monomorphism library, but I am running into an error that the classes named in the issue title are missing from LDLib in the 1.21 version.

Are they just not ported yet or is there some change in 1.21 that makes them not necessary?

Thanks

**Comment by screret** [comment]
1.21 only uses NeoForge, so they were deemed unnecessary.
