### ISSUE TITLE
jei recipe screen render issues

### ISSUE THREAD

**Issue by EasterFG** [Low-Drag-MC/LDLib-MultiLoader#41]
## What
using the ae2 pattern encoding terminal to encode the pattern, the **JEI** recipe highlighting is not in the expected position

## Additional Information
![image](https://github.com/user-attachments/assets/8aad71de-0ed4-4485-a31b-2d47ac1a6da4)

**Comment by Yefancy** [comment]
<img width="662" alt="image" src="https://github.com/user-attachments/assets/d08032cf-9b71-4d7e-9351-3463342870dc">

how to display the overlay rect?

**Comment by EasterFG** [comment]
> <img alt="image" width="662" src="https://private-user-images.githubusercontent.com/18493855/371812897-d08032cf-9b71-4d7e-9351-3463342870dc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc2MTM4MTcsIm5iZiI6MTcyNzYxMzUxNywicGF0aCI6Ii8xODQ5Mzg1NS8zNzE4MTI4OTctZDA4MDMyY2YtOWI3MS00ZDdlLTkzNTEtMzQ2MzM0Mjg3MGRjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI5VDEyMzgzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNmODRjMGU5Zjk4MGQyMGU1OTU1NDA5NDZhNDJjNDY4MzU1ZmI0NGM4YTdkNzhhMTU0ZmQ3Zjk0NTZjMWY4ZDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Xv7S13KaF5ONxPn81rlT35rSr5yL3jvHHyK5nembeRQ">
> how to display the overlay rect?

the crafting pattern and processing pattern for the required materials of the recipe exist in the AE network.

**Comment by EasterFG** [comment]
> <img alt="image" width="662" src="https://private-user-images.githubusercontent.com/18493855/371812897-d08032cf-9b71-4d7e-9351-3463342870dc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc2MTM4MTcsIm5iZiI6MTcyNzYxMzUxNywicGF0aCI6Ii8xODQ5Mzg1NS8zNzE4MTI4OTctZDA4MDMyY2YtOWI3MS00ZDdlLTkzNTEtMzQ2MzM0Mjg3MGRjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI5VDEyMzgzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNmODRjMGU5Zjk4MGQyMGU1OTU1NDA5NDZhNDJjNDY4MzU1ZmI0NGM4YTdkNzhhMTU0ZmQ3Zjk0NTZjMWY4ZDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Xv7S13KaF5ONxPn81rlT35rSr5yL3jvHHyK5nembeRQ">
> how to display the overlay rect?

你要编码的这个样板的其中一个原材料，需要在ae里面有一个合成这个原材料的样板。
比如ae里面有一个合成苹果的样板，你这个时候去写原材料包含苹果配方的样板就会出现这个问题

**Comment by Yefancy** [comment]
fixed in the ldlib 1.0.29+
