### ISSUE TITLE
[1.21.1] Latest Mod version crash game

### ISSUE THREAD

**Issue by Periam** [Low-Drag-MC/LDLib-MultiLoader#42]
After installing the latest version of LDLib, the game crash.

[latest.log](https://github.com/user-attachments/files/17176618/latest.log)
[crash-2024-09-28_18.03.35-client.txt](https://github.com/user-attachments/files/17176619/crash-2024-09-28_18.03.35-client.txt)

**Comment by desagas** [comment]
I have the same issue!

[latest.log](https://github.com/user-attachments/files/17177301/latest.log)
[debug.log](https://github.com/user-attachments/files/17177302/debug.log)
[crash-2024-09-28_20.12.44-client.txt](https://github.com/user-attachments/files/17177303/crash-2024-09-28_20.12.44-client.txt)
