### ISSUE TITLE
[1.20.1 Forge] Crash, after typing some Chinese Character into search bar of Ore Prospector(GT Modern)

### ISSUE THREAD

**Issue by AlotOfBlahaj** [Low-Drag-MC/LDLib-MultiLoader#45]
Here is the crash report
https://paste.mozilla.org/RYNmO8v9

**Comment by Yefancy** [comment]
some jvm does not support `thread.stop` anymore, I will fix it by interupt in the future

**Comment by Yefancy** [comment]
fixed
